name: workflow basico

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: atualizando codigo
        uses: actions/checkout@v2

      - name: instalando JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: buildar um projeto com maven
        run: mvn clean package --file "transporte-webflux-gj/pom.xml"

      - name: Run Tests
        run: mvn test --file "transporte-webflux-gj/pom.xml"
