spring:
  application:
    name: transporte-webflux-gj
  h2:
    console:
      enabled: true
      path: /h2-console
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password: ""
  sql:
    init:
      mode: always
      schema-locations: classpath:ddl.sql
      data-locations: classpath:data.sql
server:
  port: 8092
